// AUTO-GENERATED by scripts/gen-more-images.mjs — bouquet + banner media (Wix AI).
export const GRAZING = "https://static.wixstatic.com/media/a7fb22_1bd813238aa74ea7af7dc2c6082aee1c~mv2.png";
export const BOUQUET_IMAGES: Record<string, string> = {
  "meadow-timothy": "https://static.wixstatic.com/media/a7fb22_235e86c9f35f466cbb88acc8aab3cd1d~mv2.png",
  "wildflower-grazing-mix": "https://static.wixstatic.com/media/a7fb22_2bf792a7c99c4fd484598aa323dc00d6~mv2.png",
  "morning-pasture": "https://static.wixstatic.com/media/a7fb22_a6c5dccfa0d14813a3169da3602303ad~mv2.png",
  "first-cut-reserve": "https://static.wixstatic.com/media/a7fb22_50f5940766454723a427d6c05f13aad6~mv2.png",
  "full-meadow": "https://static.wixstatic.com/media/a7fb22_607c15f8f4d6486bafc3782afa9a33a9~mv2.png",
  "clover-dandelion-posy": "https://static.wixstatic.com/media/a7fb22_9cb0499dda51461d9353d7ecb6c62195~mv2.png"
};
// Hosted (Wix Media) copies of the footer & field scenes, so they can be served as optimized AVIF/WebP.
export const FOOTER_IMG = "https://static.wixstatic.com/media/a7fb22_bf83ce7554cc4c30a7605c1060174c63~mv2.png";
export const FIELD_IMG = "https://static.wixstatic.com/media/a7fb22_cd1e8f3526d44619ab7a87e845549212~mv2.png";
